Add scheduled_releases.yml workflow
dbt-labs/dbt-core-snapshots pull request #16
Opened 2023-03-09 19:07 UTC by colin-rogers-dbt

2023-03-09 22:15 UTC, colin-rogers-dbt commented
Successful integ tests: https://github.com/dbt-labs/dbt-core-snapshots/actions/runs/4378854587

2023-03-10 15:11 UTC, emmyoop requested changes
You're going to have to bypass the checks to get this merged in.  it runs the workflow on `main` which is why the test are failing.

2023-03-10 17:31 UTC, colin-rogers-dbt commented on test/integration/snapshot/test_create.py
> +        if ".txt" in asset_name:
I realized I should check _any_ file for being empty not just .txt

2023-03-10 17:38 UTC, colin-rogers-dbt commented on .github/workflows/scheduled_releases.yml
> +       version: ["1.1.0", "1.2.0", "1.3.0", "1.4.0", "1.4.0b1", "1.5.0b1"]
Pretty much,`1.4.0b1` maps to the 1.4 pre release that we need in cloud. 

Added a matrix comment. I'm going to follow this pr up with a pr adding documentation explaining what to do when we add a new dbt version

2023-03-10 19:37 UTC, emmyoop commented on test/integration/snapshot/test_create.py
> +        if ".txt" in asset_name:
Why not move the empty check to before the zip check?  Also, do you want to fail if it's not zip or txt.  Or that expected?

2023-03-10 19:55 UTC, colin-rogers-dbt commented on test/integration/snapshot/test_create.py
> +        if ".txt" in asset_name:
good point, cleaned up and added an else condition to raise if not txt or zip

2023-03-10 19:59 UTC, emmyoop approved these changes

2023-03-10 20:48 UTC, merged